<a href="https://colab.research.google.com/github/parth0047/Certification-/blob/main/assignments.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [32]:
import pandas as pd
df = pd.read_csv('/student-mat.csv')
print(df.head())

  school;sex;age;address;famsize;Pstatus;Medu;Fedu;Mjob;Fjob;reason;guardian;traveltime;studytime;failures;schoolsup;famsup;paid;activities;nursery;higher;internet;romantic;famrel;freetime;goout;Dalc;Walc;health;absences;G1;G2;G3
0  GP;"F";18;"U";"GT3";"A";4;4;"at_home";"teacher...
1  GP;"F";17;"U";"GT3";"T";1;1;"at_home";"other";...
2  GP;"F";15;"U";"LE3";"T";1;1;"at_home";"other";...
3  GP;"F";15;"U";"GT3";"T";4;2;"health";"services...
4  GP;"F";16;"U";"GT3";"T";3;3;"other";"other";"h...

In [33]:
df.isnull().sum()

school;sex;age;address;famsize;Pstatus;Medu;Fedu;Mjob;Fjob;reason;guardian;traveltime;studytime;failures;schoolsup;famsup;paid;activities;nursery;higher;internet;romantic;famrel;freetime;goout;Dalc;Walc;health;absences;G1;G2;G3    0
dtype: int64

In [34]:
df.dtypes

school;sex;age;address;famsize;Pstatus;Medu;Fedu;Mjob;Fjob;reason;guardian;traveltime;studytime;failures;schoolsup;famsup;paid;activities;nursery;higher;internet;romantic;famrel;freetime;goout;Dalc;Walc;health;absences;G1;G2;G3    object
dtype: object

In [26]:
df.shape

(395, 1)

In [35]:
df_cleaned = df.dropna()
df_filled = df_cleaned.fillna(df.median(numeric_only=True))
print(df_filled)

    school;sex;age;address;famsize;Pstatus;Medu;Fedu;Mjob;Fjob;reason;guardian;traveltime;studytime;failures;schoolsup;famsup;paid;activities;nursery;higher;internet;romantic;famrel;freetime;goout;Dalc;Walc;health;absences;G1;G2;G3
0    GP;"F";18;"U";"GT3";"A";4;4;"at_home";"teacher...
1    GP;"F";17;"U";"GT3";"T";1;1;"at_home";"other";...
2    GP;"F";15;"U";"LE3";"T";1;1;"at_home";"other";...
3    GP;"F";15;"U";"GT3";"T";4;2;"health";"services...
4    GP;"F";16;"U";"GT3";"T";3;3;"other";"other";"h...
..                                                 ...
390  MS;"M";20;"U";"LE3";"A";2;2;"services";"servic...
391  MS;"M";17;"U";"LE3";"T";3;1;"services";"servic...
392  MS;"M";21;"R";"GT3";"T";1;1;"other";"other";"c...
393  MS;"M";18;"R";"LE3";"T";3;2;"services";"other"...
394  MS;"M";19;"U";"LE3";"T";1;1;"other";"at_home";...

[395 rows x 1 columns]

In [ ]:
average_g3 = df_filled["G3"].mean()
print("Average G3 score:", average_g3)

In [ ]:
high_achievers = df_filled[df_filled["G3"] > 15]
count_high_achievers = high_achievers.shape[0]

print("Number of students scoring above 15 in G3:", count_high_achievers)

In [ ]:
correlation = df_filled["studytime"].corr(df_filled["G3"])
print("Correlation between study time and G3:", correlation)

In [ ]:
avg_g3_by_gender = df_cleaned.groupby("sex")["G3"].mean()
print(avg_g3_by_gender)

In [ ]:
import matplotlib.pyplot as plt

plt.figure(figsize=(8,5))
plt.hist(df_cleaned["G3"], bins=10, edgecolor="black")
plt.title("Distribution of Final Grades (G3)")
plt.xlabel("Final Grade (G3)")
plt.ylabel("Number of Students")
plt.show()

In [ ]:
import matplotlib.pyplot as plt

plt.figure(figsize=(8,5))
plt.scatter(df_cleaned["studytime"], df_cleaned["G3"], alpha=0.6)
plt.title("Study Time vs Final Grade (G3)")
plt.xlabel("Study Time (1=low, 4=high)")
plt.ylabel("Final Grade (G3)")
plt.grid(True, linestyle="--", alpha=0.6)
plt.show()

In [ ]:
import matplotlib.pyplot as plt


avg_g3_by_gender = df_cleaned.groupby("sex")["G3"].mean()
plt.figure(figsize=(6,5))
avg_g3_by_gender.plot(kind="bar", color=["skyblue", "lightcoral"], edgecolor="black")

plt.title("Average Final Grade (G3) by Gender")
plt.xlabel("Gender")
plt.ylabel("Average Final Grade (G3)")
plt.xticks(rotation=0)
plt.show()